'use strict';

angular
  .module('wcagReporter')
  /**
   * wcagSpecIdMapping
   * ---
   * Necessary version management for WCAG#IDs
   * Contains a 2-dimensional array, call it a tupple,
   * of successcriterion id versions.
   * Starting on index 0 with first id version WCAG 2.0
   * Callable like wcagSpecIdMap[SC][IDVersion].
   *
   * Current versions: [
   *  [0] => WCAG2.0,
   *  [1] => WCAG2.1
   * ]
   *
   * An empty ID version means the criterion did not exist for that version,
   * e.g.: ['', 'orientation'] means the criterion id orientation
   * was added since WCAG version 2.1
   * and ['text-equiv-all', 'non-text-content'] means the criterion id changed over time.
   * ---
   * @return Array[Array[...scId]]
   */
  .constant('wcagSpecIdMap', [
    // ids here grouped sc per array
    // From first to newest specification like: 2.0, 2.1, 2.2, 3.0?
    [
      'text-equiv-all',
      'non-text-content'
    ],
    [
      'media-equiv-av-only-alt',
      'audio-only-and-video-only-prerecorded'
    ],
    [
      'media-equiv-captions',
      'captions-prerecorded'
    ],
    [
      'media-equiv-audio-desc',
      'audio-description-or-media-alternative-prerecorded'
    ],
    [
      'media-equiv-real-time-captions',
      'captions-live'
    ],
    [
      'media-equiv-audio-desc-only',
      'audio-description-prerecorded'
    ],
    [
      'media-equiv-sign',
      'sign-language-prerecorded'
    ],
    [
      'media-equiv-extended-ad',
      'extended-audio-description-prerecorded'
    ],
    [
      'media-equiv-text-doc',
      'media-alternative-prerecorded'
    ],
    [
      'media-equiv-live-audio-only',
      'audio-only-live'
    ],
    [
      'content-structure-separation-programmatic',
      'info-and-relationships'
    ],
    [
      'content-structure-separation-sequence',
      'meaningful-sequence'
    ],
    [
      'content-structure-separation-understanding',
      'sensory-characteristics'
    ],
    [
      '',
      'orientation'
    ],
    [
      '',
      'identify-input-purpose'
    ],
    [
      '',
      'identify-purpose'
    ],
    [
      'visual-audio-contrast-without-color',
      'use-of-color'
    ],
    [
      'visual-audio-contrast-dis-audio',
      'audio-control'
    ],
    [
      'visual-audio-contrast-contrast',
      'contrast-minimum'
    ],
    [
      'visual-audio-contrast-scale',
      'resize-text'
    ],
    [
      'visual-audio-contrast-text-presentation',
      'images-of-text'
    ],
    [
      'visual-audio-contrast7',
      'contrast-enhanced'
    ],
    [
      'visual-audio-contrast-noaudio',
      'low-or-no-background-audio'
    ],
    [
      'visual-audio-contrast-visual-presentation',
      'visual-presentation'
    ],
    [
      'visual-audio-contrast-text-images',
      'images-of-text-no-exception'
    ],
    [
      '',
      'reflow'
    ],
    [
      '',
      'non-text-contrast'
    ],
    [
      '',
      'text-spacing'
    ],
    [
      '',
      'content-on-hover-or-focus'
    ],
    [
      'keyboard-operation-keyboard-operable',
      'keyboard'
    ],
    [
      'keyboard-operation-trapping',
      'no-keyboard-trap'
    ],
    [
      'keyboard-operation-all-funcs',
      'keyboard-no-exception'
    ],
    [
      '',
      'character-key-shortcuts'
    ],
    [
      'time-limits-required-behaviors',
      'timing-adjustable'
    ],
    [
      'time-limits-pause',
      'pause-stop-hide'
    ],
    [
      'time-limits-no-exceptions',
      'no-timing'
    ],
    [
      'time-limits-postponed',
      'interruptions'
    ],
    [
      'time-limits-server-timeout',
      're-authenticating'
    ],
    [
      '',
      'timeouts'
    ],
    [
      'seizure-does-not-violate',
      'three-flashes-or-below-threshold'
    ],
    [
      'seizure-three-times',
      'three-flashes'
    ],
    [
      '',
      'animation-from-interactions'
    ],
    [
      'navigation-mechanisms-skip',
      'bypass-blocks'
    ],
    [
      'navigation-mechanisms-title',
      'page-titled'
    ],
    [
      'navigation-mechanisms-focus-order',
      'focus-order'
    ],
    [
      'navigation-mechanisms-refs',
      'link-purpose-in-context'
    ],
    [
      'navigation-mechanisms-mult-loc',
      'multiple-ways'
    ],
    [
      'navigation-mechanisms-descriptive',
      'headings-and-labels'
    ],
    [
      'navigation-mechanisms-focus-visible',
      'focus-visible'
    ],
    [
      'navigation-mechanisms-location',
      'location'
    ],
    [
      'navigation-mechanisms-link',
      'link-purpose-link-only'
    ],
    [
      'navigation-mechanisms-headings',
      'section-headings'
    ],
    [
      '',
      'pointer-gestures'
    ],
    [
      '',
      'pointer-cancellation'
    ],
    [
      '',
      'label-in-name'
    ],
    [
      '',
      'motion-actuation'
    ],
    [
      '',
      'target-size'
    ],
    [
      '',
      'concurrent-input-mechanisms'
    ],
    [
      'meaning-doc-lang-id',
      'language-of-page'
    ],
    [
      'meaning-other-lang-id',
      'language-of-parts'
    ],
    [
      'meaning-idioms',
      'unusual-words'
    ],
    [
      'meaning-located',
      'abbreviations'
    ],
    [
      'meaning-supplements',
      'reading-level'
    ],
    [
      'meaning-pronunciation',
      'pronunciation'
    ],
    [
      'consistent-behavior-receive-focus',
      'on-focus'
    ],
    [
      'consistent-behavior-unpredictable-change',
      'on-input'
    ],
    [
      'consistent-behavior-consistent-locations',
      'consistent-navigation'
    ],
    [
      'consistent-behavior-consistent-functionality',
      'consistent-identification'
    ],
    [
      'consistent-behavior-no-extreme-changes-context',
      'change-on-request'
    ],
    [
      'minimize-error-identified',
      'error-identification'
    ],
    [
      'minimize-error-cues',
      'labels-or-instructions'
    ],
    [
      'minimize-error-suggestions',
      'error-suggestion'
    ],
    [
      'minimize-error-reversible',
      'error-prevention-legal-financial-data'
    ],
    [
      'minimize-error-context-help',
      'help'
    ],
    [
      'minimize-error-reversible-all',
      'error-prevention-all'
    ],
    [
      'ensure-compat-parses',
      'parsing'
    ],
    [
      'ensure-compat-rsv',
      'name-role-value'
    ],
    [
      '',
      'status-messages'
    ]
  ]);
